
export class Constants {
    // Following the format of the Dynamic blog content from Strapi
    // This constants file has been created as a fallback system, incase the dynamic content is unable to load

    static hero_title = "Blog";
    static hero_subtitle_1 = "Welcome to our blog! We will regularly post updates on the work we are doing to support the energy sector. We hope that the blog posts are informative and helpful to your business.";
    static hero_subtitle_2 = "If you would like to get involved, please contact us using our engagement form!";
    static btn1 = "Read More...";
    static hero_category = "Blog Category";
    static btn2 = "Contact us...";
    static tag_txt = "Tags";
    static social_txt = "Social Networks";
    static facebook_url = "https://www.facebook.com/fmopnigeria/";
    static linkedin_url = "https://linkedin.com/";
    static email_url = "mailto:info@power.gov.ng";
    static contact_hero_title = "Contact us";
    static contact_hero_subtitle_1 = "We would like to hear from you! If you have some questions about our data or would be interested in training about advanced data analysis, please let us know in the form below.";
    static contact_hero_subtitle_2 = "We may also be able to provide support in other areas, for example, project development of a site or conducting a joint study together.";
    static contact_hero_subtitle_3 = "Just complete the engagement form below, and we will get back to you, indicating to what extent we can support you or work together. For inspiration from our past activities, check out the blog.";
    static btn3 = "View the Blog...";
    static contact_page_txt_1 = "Engagement form";
    static contact_page_txt_2 = "Your name";
    static contact_page_txt_3 = "Your email address";
    static contact_page_txt_4 = "We'll never share your email with anyone else.";
    static contact_page_txt_5 = "Organisation name";
    static contact_page_txt_6 = "Industry or area of work of your Organisation (e.g. Solar mini-grid project developer)";
    static contact_page_txt_7 = "Please describe your question or request to us.";
    static contact_page_txt_8 = null;
    static contact_page_txt_9 = null;
    static contact_page_error_1 = "Your name is required";
    static contact_page_error_2 = "Your email is required";
    static contact_page_error_3 = "Your Organisation name is required";
    static contact_page_error_4 = "Your industry is required";
    static contact_page_error_5 = "Your question/request is required";
    static btn4 = "Send form";
    static footer_hero_title = "Stay in touch";
    static footer_hero_subtitle_1 = "Check out our blog and follow us on social media";
    static footer_hero_subtitle_2 = "to stay up to date with the latest developments.";
    static footer_hero_subtitle_3 = "#nigeriase4all";
    static form_success_hero_title = "Thanks for contacting us!";
    static form_success_hero_subtitle_1 = "We will get in touch with you about your request with the email address you provided.";
    static btn5 = "Return to homepage";
    static nav_site_title = "Nigeria Se4All";
    static nav_txt_1 = "BLOG";
    static nav_txt_2 = "MAP";
    static nav_txt_3 = "ABOUT";
    static nav_txt_url_1 = "blog";
    static nav_txt_url_2 = "https://nigeriase4all.gov.ng/map";
    static nav_txt_url_3 = "about";
    static nav_logo_url = "https://www.power.gov.ng/";
    static subscribe_hero_title = "Subscribe to our newsletter";
    static subscribe_hero_subtitle_1 = "Join our monthly newsletter and never miss out on new blog posts and promotions.";
    static subscribe_hero_txt_1 = "Email address";
    static btn6 = "Subscribe";
    static home_section1_hero = "Your partner for data and tools to support Sustainable Energy for All";
    static home_section1_subtitle1 = "Nigeria SE4ALL, an initiative from the Ministry of Power, is working with you to generate the most accurate data and latest tools to empower better electrification planning in Nigeria.";
    static home_section1_subtitle2 = "The data and tools are being continuously enriched – you can follow these updates via the blog or our social media channels at the end of the page.";
    static btn7 = "Learn more";
    static home_section2_hero = "We offer insights relevant for your industry";
    static home_section2_subtitle1 = "The tools and available data relevant to your industry can be seen through the portals here"
    static home_section3_cardtitle1 = "Mini-grids";
    static home_section3_cardsubtitle1 = "Data and site selection tools for both off-grid and interconnected mini-grids, as well market insights and tips for effective project development.";
    static home_section3_cardtitle2 = "Power Sector";
    static home_section3_cardssubtitle2 = "Focused data about grid assets and national level progress towards 30:30:30.";
    static home_section3_cardtitle3 = "Solar Home Systems";
    static home_section3_cardsubtitle3 = "Tools to support selection of distribution locations, and analysis of potential customer base.";
    static home_section4_hero = "Real-world applications and data";
    static home_section4_subtitle = "Our interactive tools and electrification data help you make better decisions";
    static home_section4_tagtitle1 = "Mini-grid";
    static home_section4_tagtitle2 = "POWER SECTOR";
    static home_section4_card1_maintitle1 = "Mini-grid site selection";
    static home_section4_card1_maintitle2 = "Select sites by distance to grid";
    static home_section4_card2_maintitle1 = "Medium Voltage grid datasets";
    static home_section4_card2_maintitle2 = "View the largest collection of medium voltage grid data for Nigeria available";
    static home_section4_card3_maintitle1 = "Real mini-grid data";
    static home_section4_card3_maintitle2 = "The mini-grid monitor publishes actual data on operational mini-grids in Nigeria";
    static home_section4_card4_maintitle1 = "The mini-grid developer toolkit";
    static home_section4_card4_maintitle2 = "You can view our entire";
    static btn8 = "View app";
    static home_section5_hero = "Stay up-to-date with our blog";
    static home_section5_subtitle = "Read about our recent activities";
    static home_section7_title1 = "OFFICE";
    static home_section7_subtitle1 = "Federal Ministry of Power <br>POWER HOUSE 14, Zambezi Crescent <br>Maitama, Abuja <br>Nigeria";
    static home_section7_title2 = "EMAIL";
    static home_section7_subtitle2 = "info@pwh.gov.ng";
    static home_section7_title3 = "WEBSITE";
    static home_section7_subtitle3 = "www.power.gov.ng";
    static home_section8_title1 = "With financial support of";
    static home_section8_title2 = "Implemented by";
    static home_section8_eu_url = "https://europa.eu/european-union/index_en";
    static home_section8_bmz_url = "http://www.bmz.de/en/index.html";
    static home_section8_giz_url = "https://www.giz.de/en/html/index.html";
    static home_section9_title1 = "Terms and conditions of service"
    static home_section9_title2 = "2021 All Rights Reserved by nigeriase4all.gov.ng";
    static home_section9_title3 = "Accreditation";
    static home_section9_url1 = "http://test.nigeriase4all.gov.ng/termsofservice";
    static home_section9_url2 = "accreditation";
    static Nav_txt_4 = "MINI-GRIDS";
    static Nav_txt_5 = "POWER SECTOR";
    static Nav_txt_6 = "SOLAR HOME SYSTEMS";
    static Nav_txt_url_4 = "mini-grids";
    static Nav_txt_url_5 = "power-sector";
    static Nav_txt_url_6 = "solar-home-systems";
    static minigrids_section2_hero = "Our interactive mini-grid maps";
    static minigrids_section2_hero_subtitle = "Explore up-to-date data via our web apps";
    static minigrids_section2_card1_title = "Off-grid mini-grid locater";
    static minigrids_section2_card1_subtitle = "Explore off-grid mini-grid locations and filter in terms of distance to grid, likely connections and economic potential.";
    static minigrids_section2_card2_title = "Interconnected mini-grid locater";
    static minigrids_section2_card2_subtitle = "View settlements connected to the grid that could be suitable for a mini-grid with pre-existing grid cover. See recommended locations from Nigeria SE4ALL based upon building count.";
    static minigrids_hero_subtitle1 = "We are supporting the continued growth of the mini-grid sector through open data and tools. We have mapped over 60km of the electricity grid and over 3.2 million off-grid buildings and built tools to assess this data.";
    static minigrids_hero_subtitle2 = "The data is enriched further through site surveys and modelling – Explore the tools below to discover more.";
    static minigrids_section3_hero = "Market intelligence"
    static minigrids_section3_subtitle = "Real time market-driven insights"
    static minigrids_section4_hero = "Data download"
    static minigrids_section4_subtitle = "Download a range of mini-grid datasets"
    static minigrids_section4_col1 = "Dataset"
    static minigrids_section4_col2 = "Last update"
    static minigrids_section4_col3 = "License"
    static minigrids_section4_col4 = "Download"
    static minigrids_section4_more = "More datasets..."
    static minigrids_section3_blog_subtitle = "Read about our recent mini-grid activities"
    static minigrids_section6_hero = "Resources and tools"
    static minigrids_section6_subtitle = "Capacity building and courses on the Learning Management Platform"
    static minigrids_section5_card1_title = "Mini-grid development toolkit"
    static minigrids_section5_card1_subtitle = "A toolkit which breaks down the potential steps in the development of a mini-grid project"
    static minigrids_section5_card2_title = "Mini-grid investment atlas"
    static minigrids_section5_card2_subtitle = "An atlas of selected mini-grid sites with potential for development"

    static accreditation_hero = "Accreditation"
    static accreditation_title1 = "Authors and web development"

    static accreditation_pt1_txt1 = "INTEGRATION environment & energy GmbH"
    static accreditation_pt1_txt2 = "mailto:ohaas@integration.org"
    static accreditation_pt1_txt3 = "Mr Oliver Haas"
    static accreditation_pt1_txt4 = "http://www.integration.org/"
    static accreditation_pt1_txt5 = "www.integration.org"
    static accreditation_pt1_img_url = "https://nigeriase4all.gov.ng/static/logos/logo-9-integration.svg"

    static accreditation_pt2_txt1 = "Reiner Lemoine Institut gGmbH"
    static accreditation_pt2_txt2 = "mailto:philipp.blechinger@rl-institut.de"
    static accreditation_pt2_txt3 = "Dr Philipp Blechinger"
    static accreditation_pt2_txt4 = "http://www.reiner-lemoine-institut.de/"
    static accreditation_pt2_txt5 = "www.reiner-lemoine-institut.de"
    static accreditation_pt2_img_url = "https://nigeriase4all.gov.ng/static/logos/logo-10-rli.png"

    static accreditation_pt3_txt1 = ""
    static accreditation_pt3_txt2 = "mailto:kingstonfortune@gmail.com"
    static accreditation_pt3_txt3 = "Fortune King"
    static accreditation_pt3_txt4 = "https://github.com/chunkingz/"
    static accreditation_pt3_txt5 = "View my portfolio"
    static accreditation_pt3_img_url = ""

    static accreditation_pt4_txt1 = "Design"
    static accreditation_pt4_txt2 = "Alsino Skowronnek"
    static accreditation_pt4_txt3 = "http://www.alsino.io/"
    static accreditation_pt4_txt4 = "www.alsino.io"

    static accreditation_pt5_txt1 = "Images"
    static accreditation_pt5_txt2 = "Features for Government: Johnny Greig Int / Alamy Stock Photo"
    static accreditation_pt5_txt3 = "Features for General public: Red Confidential / "
    static accreditation_pt5_txt4 = "http://www.shutterstock.com/"
    static accreditation_pt5_txt5 = "Shutterstock.com"
    static accreditation_pt5_txt6 = "About, Federal Ministry of Power (FMP), our mandate: Agbebiyi Adekunle Sunday / "

}
