export class PrivacyPolicyConstants {
    // Following the format of the Dynamic blog content from Strapi
    // This constants file has been created as a fallback system, incase the dynamic content is unable to load

    static pp_hero = "Privacy Policy"
    static pp_txt1 = "Introduction"
    static pp_txt1_1 = "Welcome to the Nigeria SE4All Website (“We”, Our” or “Us”) Privacy Policy."
    static pp_txt1_2_1 = "We respect your privacy and are committed to protecting your Personal Data. This Privacy Policy will inform you as to how we collect, use, share and look after your Personal Data when you visit our Website "
    static pp_txt1_2_2 = "(regardless of where you visit from) or use our Content and tell you about your privacy rights and how the law protects you."
    
    static pp_txt2 = "The Information that We Collect"
    static pp_txt2_1_1 = "We may collect personal data i.e. any information relating to an identified or identifiable natural person. An identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, "
    static pp_txt2_1_2 = "an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person; It can be anything from a name, address, "
    static pp_txt2_1_3 = "a photo, an email address, bank details, posts on social networking websites, medical information, and other unique identifier such as but not limited to MAC address, IP address, IMEI number, IMSI number, SIM, Personal Identifiable Information (PII) "
    static pp_txt2_1_4 = "and others.(‘Personal Data’)."

    static pp_txt3 = "How We Collect, Process and Share Personal Data"
    static pp_txt3_1_1 = "We may collect your Personal Data using forms, email and physical requests, cookies, JWT, web tokens, or third-party applications. You can set your browser to refuse all or some browser cookies, or to alert you if we access cookies. "
    static pp_txt3_1_2 = "If you disable or refuse cookies, please note that some parts of this Website may become inaccessible or not function properly."
    static pp_txt3_2_1 = "We may use the above-mentioned information for, human resources management; access to computer systems and third-party software; due diligence purposes; recruitment purposes; regulatory compliance; compliance with a legal obligation; "
    static pp_txt3_2_2 = "litigation; events planning and hosting; marketing, in-house security; research, analysis, and other business purposes or legitimate interests."
    static pp_txt3_3_1 = "When you send an email or other communications to us, we may retain those communications to process your inquiries, respond to your requests or improve our services provided on the Website. ends whenever you visit our website."
    static pp_txt3_3_2 = "We may also collect information in the course of providing our services to you. Our servers automatically record information that your browser s"
    
    static pp_txt4 = "Consent and Access Rights"
    static pp_txt4_1 = "We will obtain your consent before collecting or processing your Personal Data. Where we intend to use the information for a purpose other than the purpose for which it was collected, before such use, we will request your consent."
    static pp_txt4_2 = "No consent shall be sought, given or accepted in any circumstance that may engender direct or indirect propagation of atrocities, hate, child rights violation, criminal acts and anti-social conducts."
    static pp_txt4_3_1 = "You may withdraw your consent at any time and may request access to your Personal Data in our possession. Such withdrawal will not affect the lawfulness of the processing of your Personal Data prior to the withdrawal of your consent. "
    static pp_txt4_3_2 = "We can, however, deny you access to the information where we determine that your request is unreasonable."
    static pp_txt4_4 = "You have the right to request the modification or amendment of your Personal Data in our possession."
    static pp_txt4_5 = "In all cases of access or request for modification or amendment of Personal Data, we shall request sufficient identification to enable us to confirm that you are the owner of the data sought to be accessed, modified or amended."
    static pp_txt4_6_1 = "Where you provide the Personal Data of a third party to us, you confirm to us that you have informed the owner of the data about the purpose for which the data is required and that you have obtained the consent of the owner of the data "
    static pp_txt4_6_2 = "to provide the data to us for the purpose for which it is required and in accordance with this Privacy Policy."
    
    static pp_txt5 = "Personal Data Protection Principles"
    static pp_txt5_1 = "When we process your Personal Data, we are guided by the following principles. Your Personal Data shall be:"
    static pp_txt5_2 = "collected only for specific, legitimate and lawful purpose;"
    static pp_txt5_3 = "processed lawfully for the purpose for which it was collected and not further processed in a manner incompatible with such purpose(s);"
    static pp_txt5_4 = "processed adequately, accurately and without prejudice to the dignity of the human person;"
    static pp_txt5_5 = "adequate, relevant and limited to what is necessary in relation to the purpose for which it is processed;"
    static pp_txt5_6 = "accurate and where necessary, kept up to date;"
    static pp_txt5_7 = "stored only for the period within which it is reasonably needed, and"
    static pp_txt5_8 = "processed in a secure manner and protected against unauthorised or unlawful access or processing or accidental loss, destruction or damage."
    
    static pp_txt6 = "Security Measures"
    static pp_txt6_1 = "We have put in place and will maintain appropriate security measures to prevent your Personal Data from being used, accessed, altered or disclosed in an unauthorised way."
    
    static pp_txt7 = "Third Party Access"
    static pp_txt7_1 = "We may share your Personal Data with third parties in the following circumstances."
    static pp_txt7_2 = "here we have your consent;"
    static pp_txt7_3 = "Personal Data may be shared with our parent company(ies), subsidiaries or affiliates;"
    static pp_txt7_4_1 = "We provide such information to other professional advisers or other trusted businesses or persons to process Personal Data on our behalf or for other legitimate business purposes. "
    static pp_txt7_4_2 = "We would require such parties to process such information based on our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality and security measures."
    static pp_txt7_5_1 = "We have a good faith belief that access, use, preservation or disclosure of such information is reasonably necessary to (i) satisfy any applicable law, regulation, legal process or enforceable governmental request, (ii) enforce applicable terms of s"
    static pp_txt7_5_2 = "ervice, including investigation of potential violations thereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, or (iv) protect against imminent harm to our rights, property or safety as required or permitted by law."
    
    static pp_txt8 = "Transfer of Personal Data Outside the Country"
    static pp_txt8_1 = "We may transfer your Personal Data outside Nigeria in the following circumstances:"
    static pp_txt8_2 = "with your consent;"
    static pp_txt8_3 = "the transfer is necessary for important reasons of public interest;"
    static pp_txt8_4 = "the transfer is necessary for the establishment, exercise, or defence of legal claims;"
    static pp_txt8_5 = "the transfer is necessary in order to protect your vital interests; or of other persons, where you are physically or legally incapable of giving consent."
    static pp_txt8_6_1 = "Upon the transfer of information outside Nigeria, some principles of data protection may be violated in the receiving country. By consenting to the processing of your personal information, "
    static pp_txt8_6_2 = "you consent to the transfer of your personal information outside Nigeria."
    
    static pp_txt9 = "Retention of Personal Data"
    static pp_txt9_1_1 = "We will only retain your Personal Data for as long as reasonably necessary to fulfil the purposes we collected it for, including for the purposes of satisfying any legal, regulatory or tax, accounting or reporting requirements. We may retain "
    static pp_txt9_1_2 = "your Personal Data for a longer period in the event of a complaint or if we reasonably believe there is prospect of litigation in respect to our relationship with you. Where information "
    static pp_txt9_1_3 = "is kept for a longer period, such as in back up storage, or archives, such information would be safeguarded in accordance with this Privacy Policy."
    static pp_txt9_2_1 = "To determine the appropriate retention period for Personal Data, we consider the amount, nature and sensitivity of the Personal Data, the potential risk of harm from unauthorised use or disclosure of your "
    static pp_txt9_2_2 = "Personal Data, the purposes for which we process your Personal Data and whether we can achieve those purposes through other means, and the applicable legal, regulatory, reporting or other requirements."
    static pp_txt9_3 = "Where any information retained is stored in an encrypted format, considerations must be taken for secure storage of the encryption keys. Encryption keys must be retained as long as data that the keys decrypt is retained."
    static pp_txt9_4 = "In some circumstances we will anonymise your Personal Data (so that it can no longer be associated with you) for research or statistical purposes, in which case we may retain and use this information indefinitely without further notice to you."
    
    static pp_txt10 = "Violations"
    static pp_txt10_1 = "We will take swift action to remedy any suspected breaches of your Personal Data."
    static pp_txt10_2 = "We will not be responsible for any breach of your Personal Data which occurs as a result of:"
    static pp_txt10_3 = "an event which is beyond our control;"
    static pp_txt10_4 = "an act or threats of terrorism;"
    static pp_txt10_5 = "any act of God (including but not limited to fires, explosions, earthquakes, floods, epidemics, or pandemics) which compromises our data protection measures;"
    static pp_txt10_6 = "war, hostilities (whether war be declared or not), invasion, act of foreign enemies, requisition, or embargo, rebellion, revolution, insurrection, or military or usurped power, or civil war which compromises our data protection measures;"
    static pp_txt10_7 = "the transfer of your Personal Data to a third party on your instructions; or"
    static pp_txt10_8 = "the use of your Personal Data by a third party designated by you."
    static pp_txt10_9 = "Violations of this Privacy Policy by our employees may result in disciplinary action."
    
    static pp_txt11 = "Legal Rights"
    static pp_txt11_1 = "You have the right to:"
    static pp_txt11_2 = "request access to your Personal Data (commonly known as a \"data subject access request\"). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it."
    static pp_txt11_3 = "request correction of the Personal Data that we hold about you. This enables you to have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to us."
    static pp_txt11_4_1 = "request erasure of your Personal Data. This enables you to ask us to delete or remove your Personal Data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your Personal Data where you "
    static pp_txt11_4_2 = "have successfully exercised your right to object to processing, where we may have processed your information unlawfully or where we are required to erase your personal data to comply with local law. "
    static pp_txt11_4_3 = "Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request."
    static pp_txt11_5_1 = "object to processing of your Personal Data where we are relying on a legitimate interest (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground as you feel it "
    static pp_txt11_5_2 = "impacts on your fundamental rights and freedoms. You also have the right to object where we are processing your Personal Data for direct marketing purposes. "
    static pp_txt11_5_3 = "In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights and freedoms."
    static pp_txt11_6 = "request restriction of processing of your Personal Data. This enables you to ask us to suspend the processing of your Personal Data in the following scenarios:"
    static pp_txt11_7 = "If you want us to establish the data's accuracy."
    static pp_txt11_8 = "Where our use of the data is unlawful but you do not want us to erase it."
    static pp_txt11_9 = "Where you need us to hold the data even if we no longer require it as you need it to establish, exercise or defend legal claims."
    static pp_txt11_10 = "You have objected to our use of your Personal Data but we need to verify whether we have overriding legitimate grounds to use it."
    static pp_txt11_11_1 = "request the transfer of your Personal Data to you or to a third party. We will provide to you, or a third party you have chosen, your Personal Data in a structured, commonly used, machine-readable format. "
    static pp_txt11_11_2 = "Note that this right only applies to automated information which you initially provided consent for us to use or where we used the information to perform a contract with you."
    static pp_txt11_12_1 = "withdraw consent at any time where we are relying on consent to process your Personal Data. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. "
    static pp_txt11_12_2 = "If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent."
    static pp_txt11_13_1 = "You will not have to pay a fee to access your Personal Data (or to exercise any of the other rights). However, we may charge a reasonable fee if your request is clearly unfounded, repetitive, or excessive. "
    static pp_txt11_13_2 = "Alternatively, we could refuse to comply with your request in these circumstances."
    static pp_txt11_14_1 = "We may need to request specific information from you to help us confirm your identity and ensure your right to access your Personal Data (or to exercise any of your other rights). This is a security measure to ensure that your Personal Data "
    static pp_txt11_14_2 = "is not disclosed to any person who has no right to receive it. We may also contact you to ask you for further information in relation to your request to speed up our response."
    static pp_txt11_15 = "We try to respond to all legitimate requests within one (1) month. Occasionally it could take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated."
    
    static pp_txt12 = "Changes to Privacy Policy"
    static pp_txt12_1 = "We keep our Privacy Policy under regular review. This version was last updated on 1st September 2020. Historic versions can be obtained by contacting us."
    static pp_txt12_2 = "It is important that the Personal Data we hold about you is accurate and current. Please keep us informed if your Personal Data changes during your relationship with us."
    
    static pp_txt13 = "Contact Us"
    static pp_txt13_1 = "If you wish to exercise any of your rights under this Privacy Policy, or know or suspect that a breach of your Personal Data or a violation of this Privacy Policy has occurred, "
    static pp_txt13_2 = "or if you have any questions about this Privacy Policy or our privacy practices, please contact us at"
    static pp_txt13_3 = "info@power.gov.ng"
}
